// Creates a signed waiver as a Google Doc via the Drive REST API.
// No native modules required — works in Expo Go.
// When an EAS build is available, swap this file's implementation for expo-print.

import { WaiverSection } from '@/constants/waivers';
import { WaiverRecord } from '@/services/firestore';

const KBC_ADMIN_EMAIL = 'kingstonboulderingcooperative@gmail.com';

// ─── HTML builder ────────────────────────────────────────────────────────────

function formatSignedDate(iso: string) {
  const d = new Date(iso);
  return (
    d.toLocaleDateString([], { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) +
    ' at ' +
    d.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })
  );
}

function buildHtml(
  fullTitle: string,
  memberName: string,
  sections: readonly WaiverSection[],
  record: WaiverRecord,
): string {
  const signedBy      = record.guardian ?? record.signedBy;
  const guardianLabel = record.guardian ? ' (Legal Guardian)' : '';
  const onBehalf      = record.guardian
    ? `<div class="sig-row"><span class="lbl">Minor: </span><b>${record.signedBy}</b></div>`
    : '';

  const body = sections.map(s => {
    const t = s.text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    switch (s.type) {
      case 'heading': return `<h3>${t}</h3>`;
      case 'warning': return `<p class="warn">${t}</p>`;
      case 'consent': return `<p class="consent">${t}</p>`;
      default:        return `<p>${t}</p>`;
    }
  }).join('\n');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<style>
  body{font-family:Arial,sans-serif;font-size:13px;color:#222;max-width:750px;margin:40px auto;padding:0 24px;line-height:1.65}
  h1{font-size:22px;border-bottom:3px solid #c0005a;padding-bottom:8px}
  .sub{font-size:12px;color:#777;margin:4px 0 24px}
  h3{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-top:20px;border-top:1px solid #eee;padding-top:10px}
  p{margin:10px 0}
  .warn{background:#fff8e1;border-left:4px solid #f0c040;padding:10px 14px;font-weight:bold;color:#7a5c00}
  .consent{font-style:italic;color:#555;border-top:1px solid #eee;padding-top:10px;margin-top:10px}
  .sig{margin-top:32px;border:2px solid #4db847;border-radius:8px;padding:20px;background:#f0fdf0}
  .sig h2{color:#2d6a2d;font-size:15px;margin:0 0 14px}
  .sig-row{margin:6px 0;font-size:13px}
  .lbl{color:#666}
  footer{margin-top:40px;font-size:11px;color:#aaa;text-align:center;border-top:1px solid #eee;padding-top:12px}
</style>
</head><body>
<h1>KBC Membership Form and Waiver</h1>
<p class="sub">${fullTitle}<br/>Kingston Bouldering Co-operative · kbc.climb@gmail.com</p>
${body}
<div class="sig">
  <h2>✅ Electronically Signed</h2>
  <div class="sig-row"><span class="lbl">Member: </span><b>${memberName}</b></div>
  <div class="sig-row"><span class="lbl">Signed by: </span><b>${signedBy}${guardianLabel}</b></div>
  ${onBehalf}
  <div class="sig-row"><span class="lbl">Date &amp; Time: </span><b>${formatSignedDate(record.signedAt)}</b></div>
</div>
<footer>Generated by KBC App · Kingston Bouldering Co-operative</footer>
</body></html>`;
}

// ─── Drive API helpers ───────────────────────────────────────────────────────

async function driveUpload(html: string, docName: string, accessToken: string): Promise<string> {
  const boundary = 'kbc_wb_' + Date.now();
  const metadata = JSON.stringify({
    name: docName,
    mimeType: 'application/vnd.google-apps.document',
  });

  const body =
    `--${boundary}\r\n` +
    `Content-Type: application/json; charset=UTF-8\r\n\r\n` +
    `${metadata}\r\n` +
    `--${boundary}\r\n` +
    `Content-Type: text/html; charset=UTF-8\r\n\r\n` +
    `${html}\r\n` +
    `--${boundary}--`;

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body,
    },
  );

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Drive upload failed (${res.status}): ${err}`);
  }
  const json = await res.json();
  return json.webViewLink as string;
}

async function shareWithAdmin(fileId: string, accessToken: string): Promise<void> {
  // Extract file ID from webViewLink if needed
  const res = await fetch(
    `https://www.googleapis.com/drive/v3/files/${fileId}/permissions?sendNotificationEmail=false`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ type: 'user', role: 'reader', emailAddress: KBC_ADMIN_EMAIL }),
    },
  );
  // Non-critical — log but don't throw
  if (!res.ok) console.warn('Could not share doc with admin:', await res.text());
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Creates a signed waiver Google Doc in the user's Drive,
 * shares it with the KBC admin, and returns the webViewLink.
 *
 * Replace this implementation with expo-print after the EAS build.
 */
export async function createWaiverDoc(
  fullTitle: string,
  memberName: string,
  sections: readonly WaiverSection[],
  record: WaiverRecord,
  accessToken: string,
): Promise<string> {
  const date    = new Date(record.signedAt).toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' });
  const docName = `KBC Waiver — ${memberName} — ${date}`;
  const html    = buildHtml(fullTitle, memberName, sections, record);

  const webViewLink = await driveUpload(html, docName, accessToken);

  // Extract file ID from the webViewLink for sharing
  const match  = webViewLink.match(/\/d\/([^/]+)\//);
  const fileId = match?.[1];
  if (fileId) await shareWithAdmin(fileId, accessToken);

  return webViewLink;
}
